# Site settings
title: A blog about batho2n
description: A blog about signal processing
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: batho2n
user_description: DSP Developer
user_title: DSP Developer
email: batho2n@kaist.ac.kr
github_username: batho2n

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
